name: Continuous Integration

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version:
                    - 7.3  # from 2018-12 to 2020-12 (2021-12)
                    - 7.4  # from 2019-11 to 2021-11 (2022-11)
                    - 8.0  # from 2020-11 to 2022-11 (2023-11)
                    - 8.1  # from 2021-11 to 2023-11 (2025-12)
                    - 8.2  # from 2022-12 to 2024-12 (2026-12)
                    - 8.3  # from 2023-11 to 2025-12 (2027-12)
                    - 8.4  # from 2024-11 to 2026-12 (2028-12)
                    - 8.5  # from 2025-11 to 2027-12 (2029-12)

        # Prevent unsupported versions of PHP to fail the CI run
        continue-on-error: ${{ contains(fromJson('[ "7.3", "7.4", "8.0", "8.1", "8.2" ]'), matrix.php-version) == false }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}

            - name: Validate composer.json
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run test suite
              run: php vendor/bin/phpunit
